Soft mode
peggyjs/peggy pull request #502
Opened 2024-03-05 08:51 UTC by frostburn

ref #501

2025-04-08 22:02 UTC, hildjj commented
Once #593 lands, can you rebase this, please?  I'll play around with it to see if it makes sense to go into the next major release.  I think there's a semver-major breaking change with existing grammars that use the custom option `soft`.

We will also need docs, but don't bother with those until this gets rebased and I try it out.

2025-04-17 20:11 UTC, hildjj commented
ok, I'm ready for this to be rebased, please.

2025-04-18 18:19 UTC, frostburn commented
Rebased. CI tests seem to pass even though locally I have three tests failing when running `nve latest npm test` on `main` and on this branch.

2025-04-18 20:09 UTC, hildjj commented
Great.  I will take a look at this and make a crisp decision before landing #602.

2025-04-18 20:40 UTC, hildjj commented
Can you remove node_modules, do `pnpm i -r` and see if your local errors go away, please?

2025-04-18 20:47 UTC, hildjj requested changes
Should there be a command line option?
lib/peg.d.ts needs to be updated, as well as the type tests in test/types/peg.test-d.ts

2025-04-18 20:47 UTC, hildjj commented on lib/.eslintrc.json
This file isn't used anymore, and we should be in ES2020 on main, so this shouldn't be needed anyway, I hope.

2025-04-18 20:47 UTC, hildjj commented on lib/compiler/passes/generate-js.js
> +      "  var success = (peg$result !== peg$FAILED && peg$currPos === input.length);",
this should be `const` now instead of `var`.

2025-04-18 20:47 UTC, hildjj commented on lib/compiler/passes/generate-js.js
> +      "     return {result: peg$result, success, fail};",
If `success` is true, maybe `fail` should be undefined?  Calling it will always give unexpected results on success.

2025-04-18 20:47 UTC, hildjj commented on test/api/generated-parser-api.spec.js
> +      expect(result.result).to.equal("a");
Check that fail is undefined.

2025-04-18 20:47 UTC, hildjj commented
Overall, I'm +1 on this, but it needs a few tweaks.

2025-04-19 13:41 UTC, hildjj commented
Apologies, but I just realized that this code should build on the peg$library option.  It makes sense for the results from that to include the the `fail()` function.  That would give you everything you need, I think, except for the nicer ergonomics that your approach has.

2025-04-21 13:59 UTC, frostburn commented
> Can you remove node_modules, do `pnpm i -r` and see if your local errors go away, please?

They do not. I'll chalk it off to running an old Ubuntu locally.

2025-04-21 14:12 UTC, hildjj commented
Can you copy over the error you're seeing into this discussion, please?

2025-04-21 15:11 UTC, frostburn commented
Changed `fail()` to `peg$throw()` and used library mode for everything.

2025-04-21 16:31 UTC, hildjj commented
Oh.  That's because you had a test fail, and you need to clean up the files that got left over.  Delete the files that the error says, and it it should work cleanly.

2025-04-22 13:42 UTC, hildjj requested changes
Two minor nits and this is ready to go.

2025-04-22 18:16 UTC, frostburn commented on docs/js/examples.js
> +  const peg$SUCCESS = (peg$result !== peg$FAILED && peg$currPos === input.length);
I used `peg$success`. I'll leave removing the `peg$` prefix for later work on stabilization of the library API.

2025-04-22 23:16 UTC, merged

2025-04-22 23:16 UTC, hildjj commented
Thanks!