Update documentation.html
peggyjs/peggy pull request #506
Opened 2024-03-30 17:22 UTC by Flamenco

Add "END OF INPUT" syntax and example.

2024-03-30 17:28 UTC, hildjj commented
Please ensure you are in the AUTHORS file and add a changelog entry.

2024-03-30 17:39 UTC, Flamenco commented
OK.  I need to the the example working.  I am not sure how it works, so  I will remove it for now.

2024-03-30 18:01 UTC, hildjj commented
To get the examples to work, add your example to `docs/js/examples.peggy` and run `npm run examples` to build.

2024-03-30 18:05 UTC, Flamenco commented
Thanks!  I will update the PR with examples later today.

2024-03-30 18:11 UTC, Mingun commented
I think, that you should specially mention, that this is only composite rule which is constructed from two parts. Actually, everyone can approach to this solution, but it may not be immediately obvious.

2024-03-30 18:21 UTC, hildjj commented
Maybe let's add a section for composite rules? we can add more to it later as desired.

2024-03-31 01:31 UTC, Flamenco commented
Its amazing how little information on the web there is about this EOI syntax.  I left the example next to the `.` example for now, because they are related to each other.

2024-04-01 16:26 UTC, hildjj requested changes

2024-04-01 16:26 UTC, hildjj commented on docs/js/examples.peggy
> +
Sorry, this is a nitpick, but can you move your new rule above `rest` please?

2024-04-01 16:26 UTC, hildjj commented on docs/documentation.html
> +      or patterns up to the end of input. This is a composite rule;
"patterns up to the end of the rule" isn't clear.  I think you mean that it's useful when used as a predicate, but we probably need some more words.

2024-04-01 16:26 UTC, hildjj commented on docs/documentation.html
> +      It should NOT be placed inside a character set or quote.
This line seems obvious to me (we don't say this about any of the other primitives), and as such, it was confusing.  Maybe remove?

2024-04-01 21:34 UTC, Flamenco commented
I just trimmed off the fat and kept it simple.  I was not sure if including the rebuild peggy.js was appropriate.

2024-04-04 00:41 UTC, Flamenco commented
Not sure why my second commit did not show up, but it is now aligned with your comments.

2024-04-04 05:01 UTC, hildjj approved these changes

2024-04-04 05:01 UTC, merged